### ISSUE TITLE
New PrivateKey result in q=NULL

### ISSUE THREAD

**Issue by AliD201** [juanelas/paillier-bigint#9]
Greetings hope you are doing well 
i am saving the private key and loading it again

when it is saved it showed as 
```
lambda: 2385128274998604186348365713560752968760405693505101775118516919851343466617545084168730919590431984722960235639807801309473610654474668626657999131708989625473845831016134764748121799156852049443164020599869321359217130616448044729179882742660109412744034702572502677041213980341841433873892716315804279162033263694832843262854216862179439882226029587827502632430499229885692432298117362891266842261359722415154205549214063784336006501313745233511330109769127714724620623943199526303448837404177743121009092100254844757824123591774224888704420211127233018588942124443461742603800425960621498594936120724362659233509526755357103794867118599779567940538716769473094947135635267931896658069685140762895817920906045573541584345349135593275508554900986767271590614299893155934201850521402669871837424141242526615236905746970866085469609917249101274762120229917245620965325837991934692544176487045181318972862545942747693709832324n
mu: 4568304398421090445630397328660877292304485369792641475046671773738216190320458962212349119327235994374298504022894372560528915554539097636424104261566556612519754378003491092703166489575303510268015358716431088917065491852901296210847330434172474198852403121069463502382505311934404349826511995099926699473995782468832020845076671070374906795947229381231291957170182369382581223137833897760030983620328213060866690355341775318769293494905852494012637165622299095770806444425186677632373922238172686015447071980759848553602348086690343280154269056309738362667881063147599715823808051478553471317411023525712339397006371848080319873597711167289984567255952373924998510034994291794367634144783572794762347678039420268406776521647668996231971334518831937104606968815498462909114281446705895502431776757357308623552695815013156773355343276103014380686549539112295547015984136057785817683176136672857058836433997863448608590310967n
publicKey: {n: 47702565499972083726967314271215059375208113870102…031018442042889282893013956243937859173086151123n, _n2: 22755347552791268943142856300817423043209652531184…775339559780711596276556460948947024573994161129n, g: 40629503159831689364544031656142975259609390898827…372756798035934082120253850411135556651331732461n}
_p: 3571018152498762822201638720943960867597758523598992333150088336483347773956242222803065448213364822079795941987284598320387412113923424154497407726624666327835817416920056810973935679084046545592258347113232981850935984710161168773450320713975118639905553097371115690332878196142872363906864252453999198040101077198042912729635165524596579535691644604641544953609096446146746084836893723535956803565063381466721875510983986307483560346289083703974648131439537949n
_q: 1335825343441420948126677293262852446047779831894829012332745894816549727649930579951020381921521603081172523534784759453778782849435179106751228428304741951179058291419357176329623116924977223835617550676814599525796621425433252230184866610250689981082402354549991151666439348561120985485323285378424000818875811447696587585306952201982016889410151146295447221370169603675491057767959940105718423869280264294753038134946102761315359908779147448077715654226948527n

```
but when trying to load it from this object ( creating new private key )
it shows this 
```
lambda: 2385128274998604186348365713560752968760405693505101775118516919851343466617545084168730919590431984722960235639807801309473610654474668626657999131708989625473845831016134764748121799156852049443164020599869321359217130616448044729179882742660109412744034702572502677041213980341841433873892716315804279162033263694832843262854216862179439882226029587827502632430499229885692432298117362891266842261359722415154205549214063784336006501313745233511330109769127714724620623943199526303448837404177743121009092100254844757824123591774224888704420211127233018588942124443461742603800425960621498594936120724362659233509526755357103794867118599779567940538716769473094947135635267931896658069685140762895817920906045573541584345349135593275508554900986767271590614299893155934201850521402669871837424141242526615236905746970866085469609917249101274762120229917245620965325837991934692544176487045181318972862545942747693709832324n
mu: 4568304398421090445630397328660877292304485369792641475046671773738216190320458962212349119327235994374298504022894372560528915554539097636424104261566556612519754378003491092703166489575303510268015358716431088917065491852901296210847330434172474198852403121069463502382505311934404349826511995099926699473995782468832020845076671070374906795947229381231291957170182369382581223137833897760030983620328213060866690355341775318769293494905852494012637165622299095770806444425186677632373922238172686015447071980759848553602348086690343280154269056309738362667881063147599715823808051478553471317411023525712339397006371848080319873597711167289984567255952373924998510034994291794367634144783572794762347678039420268406776521647668996231971334518831937104606968815498462909114281446705895502431776757357308623552695815013156773355343276103014380686549539112295547015984136057785817683176136672857058836433997863448608590310967n
publicKey: 3571018152498762822201638720943960867597758523598992333150088336483347773956242222803065448213364822079795941987284598320387412113923424154497407726624666327835817416920056810973935679084046545592258347113232981850935984710161168773450320713975118639905553097371115690332878196142872363906864252453999198040101077198042912729635165524596579535691644604641544953609096446146746084836893723535956803565063381466721875510983986307483560346289083703974648131439537949n
_p: 1335825343441420948126677293262852446047779831894829012332745894816549727649930579951020381921521603081172523534784759453778782849435179106751228428304741951179058291419357176329623116924977223835617550676814599525796621425433252230184866610250689981082402354549991151666439348561120985485323285378424000818875811447696587585306952201982016889410151146295447221370169603675491057767959940105718423869280264294753038134946102761315359908779147448077715654226948527n
_q: null
bitLength: [Exception: TypeError: Cannot convert undefined to a BigInt at BigInt (<anonymous>) at bitLength (http://localhost:3000/static/js/0.chunk.js:555:7) at PrivateKey.get bitLength [as bitLength] (http://localhost:3000/static/js/0.chunk.js:6761:81) at PrivateKey.o (<anonymous>:1:83)]
n: undefined
```

the code simply as follows :
```js
      let y =  new paillierBigint.PrivateKey(privateKey.lambda, privateKey.mu, privateKey._p , privateKey._q)

```
and the `privateKey` is equivalent to the first text
I tried to print the _q and it does exist so there is something going on with the contractor probably

**Comment by AliD201** [comment]
Sorry, i noticed i  didn't pass the public key.... my bad. 

and i spent hours on this -.-" unnoticed
